apiVersion: apps/v1
kind: Deployment
metadata:
  name: prd-carrinhodigital-webapi
  labels:
    app: carrinhodigital-webapi
    env: prd
spec:
  selector:
    matchLabels:
      app: carrinhodigital-webapi
      env: prd
  template:
    metadata:
      labels:
        app: carrinhodigital-webapi
        env: prd
    spec:
      containers:
        - name: prd-redis-socket-connections
          image: redis:6.0-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "200M"
            limits:
              cpu: "250m"
              memory: "400M"
        - name: prd-carrinhodigital-webapi
          image: gcr.io/carrinhodigital/webapi:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "150m"
              memory: "500M"
            limits:
              cpu: "250m"
              memory: "1G"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: prd-carrinhodigital-configmap
            - secretRef:
                name: prd-carrinhodigital-secrets
          volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/config
      imagePullSecrets:
        - name: gcr-docker-image-credentials
      volumes:
        - name: gcp-credentials
          configMap:
            name: prd-gcp-configmap
            items:
              - key: application-credentials
                path: google_application_credentials.json
