apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: carrinhodigital-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  rules:
    - host: api.carrinhodigital.co
      http:
        paths:
          - path: /
            backend:
              serviceName: prd-carrinhodigital-service
              servicePort: 80
          - path: /
            backend:
              serviceName: prd-carrinhodigital-service
              servicePort: 443
  tls:
    - secretName: secret-tls
