apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prd-carrinhodigital-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.carrinhodigital.co
      http:
        paths:
          - path: /
            backend:
              serviceName: prd-carrinhodigital-service
              servicePort: 80
