apiVersion: v1
kind: Service
metadata:
  name: prd-carrinhodigital-service
  labels:
    app: carrinhodigital-webapi-service
    env: prd
spec:
  selector:
    app: carrinhodigital-webapi
    env: prd
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
