version: "3"

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    networks:
      - dnet

  mongodb:
    image: mongo
    restart: always
    networks:
      - dnet
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  webapi:
    build: ../
    ports:
      - "8000:8000"
    networks:
      - dnet
    env_file:
      - ../.env

networks:
  dnet:
    driver: bridge
