version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - dnet
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  webapi:
    build: ../
    ports:
      - "8001:8001"
    networks:
      - dnet
    environment:
      - PORT=8001
      - MONGODB_URI=mongodb://root:example@mongodb:27017/admin
      - SALT=12
      - SECRET=secret
      - ISSUER=MercadoOnlinePlataform
      - AUDIENCE=MercadoOnlineAudience
      - EXPIRE_IN_MINUTES=240
      - NODE_ENV=development

networks:
  dnet:
    driver: bridge
