name: WebAPI-CD-DigitalOcean-k8s

on:
  push:
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  PROJECT_ID: carrinhodigital
  DOCKER_IMAGE: gcr.io/carrinhodigital/webapi:latest
  K8S_DIR: ${{ github.workspace }}/k8s/prd
  K8S_SECRETS_DIR: ${{ github.workspace }}/k8s/prd/prd-secrets.yml
  CLUSTER_NAME: "kubernetes-prod-cluster"

jobs:
  setup-publish-kuberntes-files:
    name: "Setup K8S Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Replace $(SALT)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          salt: ${{ secrets.SALT }}

      - name: Replace $(SECRET)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          secret: ${{ secrets.SECRET }}

      - name: Replace $(ISSUER)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          issuer: ${{ secrets.ISSUER }}

      - name: Replace $(AUDIENCE)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          audience: ${{ secrets.AUDIENCE }}

      - name: Replace $(BUCKET_NAME)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          bucket_name: ${{ secrets.BUCKET_NAME }}

      - name: Replace $(MONGODB_URI)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          mongodb_uri: ${{ secrets.MONGODB_URI }}

      - name: Replace $(FACEBOOK_APP_ID)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          facebook_app_id: ${{ secrets.FACEBOOK_APP_ID }}

      - name: Replace $(FACEBOOK_APP_SECRET)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          facebook_app_secret: ${{ secrets.FACEBOOK_APP_SECRET }}

      - name: Replace $(GOOGLE_DISTANCE_MATRIX_API_KEY)
        uses: BjornLuG/substitute-string-action@v1
        with:
          _input-file: ${{ env.K8S_SECRETS_DIR }}
          _format-key: "%%key%%"
          google_distance_matrix_api_key: ${{ secrets.GOOGLE_DISTANCE_MATRIX_API_KEY }}

      - name: Create GCP Application Credentials
        run: |
          cat > ${{ env.K8S_DIR }}/../application-credentials.json <<EOF
            ${{ secrets.GCP_JSON_APP_KEY }}
          EOF

      - name: Create GCP Application Credentials
        run: |
          cat ${{ env.K8S_SECRETS_DIR }}
      # - name: Create DigitalOcean kubeconfig
      #   run: |
      #     doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}
      # - name: Deploy k8s files to cluster
      #   run: |
      #     kubectl apply -f ${{ env.K8S_DIR }}
