name: WebAPI-CD-DigitalOcean-k8s

on:
  push:
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  PROJECT_ID: carrinhodigital
  DOCKER_IMAGE: gcr.io/carrinhodigital/webapi:latest
  K8S_DIR: ${{ github.workspace }}/k8s/prd
  K8S_SECRETS_DIR: ${{ github.workspace }}/k8s/prd/prd-secrets.yml
  CLUSTER_NAME: "kubernetes-prod-cluster"

jobs:
  setup-publish-kuberntes-files:
    name: "Setup K8S Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Replace $(SALT)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_salt%%"
          replace: ${{ secrets.SALT }}

      - name: Replace $(SECRET)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_secret%%"
          replace: ${{ secrets.SECRET }}

      - name: Replace $(ISSUER)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_issuer%%"
          replace: ${{ secrets.ISSUER }}

      - name: Replace $(AUDIENCE)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_audience%%"
          replace: ${{ secrets.AUDIENCE }}

      - name: Replace $(BUCKET_NAME)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_bucket_name%%"
          replace: ${{ secrets.BUCKET_NAME }}

      - name: Replace $(MONGODB_URI)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_mongodb_uri%%"
          replace: ${{ secrets.MONGODB_URI }}

      - name: Replace $(FACEBOOK_APP_ID)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_facebook_app_id%%"
          replace: ${{ secrets.FACEBOOK_APP_ID }}

      - name: Replace $(FACEBOOK_APP_SECRET)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_facebook_app_secret%%"
          replace: ${{ secrets.FACEBOOK_APP_SECRET }}

      - name: Replace $(GOOGLE_DISTANCE_MATRIX_API_KEY)
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "%%prd_google_distance_matrix_api_key%%"
          replace: ${{ secrets.GOOGLE_DISTANCE_MATRIX_API_KEY }}

      - name: Create GCP Application Credentials
        run: |
          cat > ${{ env.K8S_DIR }}/../application-credentials.json <<EOF
            ${{ secrets.GCP_JSON_APP_KEY }}
          EOF

      - name: Create DigitalOcean kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}

      - name: Install Ingress Controller
        run: |
          helm repo add nginx-stable https://helm.nginx.com/stable
          helm repo update

          helm install nginx-ingress nginx-stable/nginx-ingress --set controller.publishService.enabled=true

      - name: Deploy k8s files to cluster
        run: |
          kubectl apply -f ${{ env.K8S_DIR }}
